### ISSUE TITLE
Only prints the Given gherkin steps, not When, And or Then

### ISSUE THREAD

**Issue by JEHAL981** [johanvaniperen/wdio-cucumber-snippet-reporter#5]
Great Work here @johanvaniperen , thanks 👍  🥇 
Seems to print all steps as Givens not the When, And or Then syntax for the steps.  Looking at the code it only prints the steps  in 'Given's.  It's a not major problem as the work around is to replace the steps with the correct gherkin syntax.

**Comment by johanvaniperen** [comment]
The problem is that the pre-condition (Given, When or Then) is not passed by the baseReporter data. It's the same problem other reporters have also (spec, allure). I have to dive further into it or raise this issue with the webdriver.io team. Will have a look on it later.

**Comment by JEHAL981** [comment]
Do feel the wdio-cucumber-framework needs to be rewritten similar to Nightwatch and protractor, were those frameworks use the cucumber lib APIs.

**Comment by anilkoithara** [comment]
Any Update on this ?
