### ISSUE TITLE
No output on console

### ISSUE THREAD

**Issue by ghost** [johanvaniperen/wdio-cucumber-snippet-reporter#6]
Doesn't work for me. I can't find the reason...

My output:

[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] My search feature
[chrome #0-0]
[chrome #0-0]     Search for specific cars
[chrome #0-0]       √ open the webapp
[chrome #0-0]       1) I type some brand
[chrome #0-0]       2) expect a result
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 passing (12s)
[chrome #0-0] 2 failing
[chrome #0-0]
[chrome #0-0] 1) Search for specific cars8 I type some brand:
[chrome #0-0] Step "I type some brand" is not defined. You can ignore this error by setting
                              cucumberOpts.ignoreUndefinedDefinitions as true.
[chrome #0-0] undefined:undefined
[chrome #0-0]
[chrome #0-0] 2) Search for specific cars8 expect a result:
[chrome #0-0] Step "expect a result" is not defined. You can ignore this error by setting
                              cucumberOpts.ignoreUndefinedDefinitions as true.
[chrome #0-0] undefined:undefined
[chrome #0-0]

1 passing (13.40s)
2 failing

1) Search for specific cars8 I type some brand:
Step " I type some brand" is not defined. You can ignore this error by setting
                              cucumberOpts.ignoreUndefinedDefinitions as true.
running chrome
undefined:undefined

2) Search for specific cars8  expect a result:
Step " expect a result" is not defined. You can ignore this error by setting
                              cucumberOpts.ignoreUndefinedDefinitions as true.
running chrome
undefined:undefined

```
 "dependencies": {
    "babel-preset-env": "^1.7.0",
    "chai": "^4.1.2",
    "eslint": "^4.19.1",
    "wdio-cucumber-snippet-reporter": "0.0.4",
    "wdio-spec-reporter": "^0.1.4",
    "webdriverio": "^4.12.0"
  },
  "devDependencies": {
    "wdio-cucumber-framework": "^2.1.0",
    "wdio-json-reporter": "^0.3.1",
    "wdio-junit-reporter": "^0.4.3"
  }
```

wdio.conf.js

  ` reporters: ['dot', 'spec', 'cucumber-snippet'],`

**Comment by johanvaniperen** [comment]
Little bit late, but 

cucumberOpts setting ignoreUndefinedDefinitions must be set to true

Does this solve the problem?

**Comment by johanvaniperen** [comment]
updated Readme.md

**Comment by ghost** [comment]
This solved the problem! Thank you
